language: r
warnings_are_errors: true
apt_packages:
- pgf
r_packages:
- covr
r_binary_packages:
- testthat
- knitr
after_success:
- Rscript -e 'library(covr);codecov(exclusions="R/Deprecated.R")'
notifications:
  email:
    on_success: change
    on_failure: change
